# Site settings
title: Code Hospital
email: maysam@codehospital.com
description: maysam torabi
moto: Your Idea is Your Baby, we help you deliver a Healthy Product.
url: http://www.codehospital.com
keywords: "Ruby on Rails, Elixir Phoenix, React Typescript Developer"
skills: "Web Developer - Backend Developer - Database Designer"
meta_author: Torabi, Maysam

# contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/freemaysam
  - title: facebook
    url: http://facebook.com/maysamtorabi
  - title: stack-overflow
    url: http://stackoverflow.com/users/348701/maysam
  - title: bitbucket
    url: http://bitbucket.org/maysam
  - title: github
    url: http://github.com/codehospital
  - title: linkedin
    url: https://www.linkedin.com/in/maysam/
  - title: freelancer
    url: https://www.freelancer.com/u/maysam

# Postal address (add as many lines as necessary)
address:
  - line: Basel, Switzerland

# Build settings
markdown: kramdown
permalink: pretty
